name: Code Fix and Build Check

on:
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  fix-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: List installed packages
        run: pnpm list --depth=0

      - name: Run code formatting
        run: pnpm fix

      - name: Commit and push changes if any
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git diff --quiet --exit-code || git commit -am "Auto-fix: Code formatting" || echo "No changes to commit"
          git push || echo "Nothing to push"

      - name: Build check
        run: |
          git switch -c temp-build-check
          git merge origin/develop
          pnpm build
          git switch ${{ github.event.pull_request.head.ref }}
